"""
gui.py — System Assembly & Interface Layer for the Smart Agriculture DSS.

This module provides a Tkinter-based Graphical User Interface that binds
the three serialized ML models into a single interactive application.
Features:
- Premium Dark Theme styling using HSL tailored colors.
- Interactive farm parameter inputs with validation and sample presets.
- Sequential model inference: Crop suggestion, soil zoning, and yield forecasting.
- Pre-rendered matplotlib plots displayed via native Tk PhotoImage (no PIL required).
"""

import os
import sys
import json
import tkinter as tk
from tkinter import ttk, messagebox
import numpy as np
import joblib

# Add src to python path if run directly
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from utils import (
    DECISION_TREE_MODEL, KMEANS_MODEL, LINEAR_REG_MODEL,
    RESULTS_DIR, ALL_FEATURES, SOIL_FEATURES,
    ensure_dirs, setup_logger
)

logger = setup_logger("gui")

# ──────────────────────────────────────────────
# COLOR PALETTE DEFINITIONS (Premium Dark Theme)
# ──────────────────────────────────────────────
BG_MAIN = "#121214"
BG_CARD = "#1a1a1f"
ACCENT_CYAN = "#00f5ff"
ACCENT_PURPLE = "#a29bfe"
ACCENT_GREEN = "#2ecc71"
ACCENT_ORANGE = "#ff9f43"
TEXT_WHITE = "#ffffff"
TEXT_SILVER = "#b2bec3"
TEXT_DARK = "#2d3436"
BORDER_COLOR = "#2d2d35"

# Pre-rendered plot image paths (generated by models.py)
PLOT_FEATURE_IMPORTANCE = os.path.join(RESULTS_DIR, "feature_importance.png")
PLOT_CLUSTER_SCATTER = os.path.join(RESULTS_DIR, "cluster_scatter.png")
PLOT_RESIDUAL = os.path.join(RESULTS_DIR, "residual_analysis.png")


class SmartAgriGUI(tk.Tk):
    def __init__(self):
        super().__init__()

        self.title("Smart Agriculture Decision Support System (DSS)")
        self.geometry("1280x820")
        self.configure(bg=BG_MAIN)
        self.minsize(1000, 700)

        ensure_dirs()
        self.load_artifacts()
        self.create_styles()
        self.build_ui()

    # ──────────────────────────────────────────
    # Model & Data Loading
    # ──────────────────────────────────────────
    def load_artifacts(self):
        """Load all serialized ML models and metrics."""
        self.models_loaded = False
        try:
            if not os.path.exists(DECISION_TREE_MODEL):
                raise FileNotFoundError(f"Decision Tree model not found at {DECISION_TREE_MODEL}")
            self.dt_clf = joblib.load(DECISION_TREE_MODEL)

            if not os.path.exists(KMEANS_MODEL):
                raise FileNotFoundError(f"K-Means bundle not found at {KMEANS_MODEL}")
            self.kmeans_bundle = joblib.load(KMEANS_MODEL)
            self.kmeans = self.kmeans_bundle["kmeans"]
            self.soil_scaler = self.kmeans_bundle["scaler"]

            if not os.path.exists(LINEAR_REG_MODEL):
                raise FileNotFoundError(f"Linear Regression model not found at {LINEAR_REG_MODEL}")
            self.lr_model = joblib.load(LINEAR_REG_MODEL)

            self.load_metrics_data()
            self.models_loaded = True
            logger.info("All ML models and metadata loaded successfully.")
        except Exception as e:
            logger.error(f"Error loading model artifacts: {e}")
            messagebox.showerror(
                "Model Loading Failure",
                f"Could not load ML models.\nRun preprocessing.py then models.py first!\n\nError: {e}"
            )
            self.dt_clf = None
            self.kmeans = None
            self.lr_model = None

    def load_metrics_data(self):
        """Load metric json files for displaying precision and bounds."""
        self.residual_std = 5.13
        self.agronomic_guidance = {}

        km_metrics_path = os.path.join(RESULTS_DIR, "kmeans_metrics.json")
        lr_metrics_path = os.path.join(RESULTS_DIR, "linear_regression_metrics.json")

        if os.path.exists(km_metrics_path):
            with open(km_metrics_path, "r") as f:
                km_data = json.load(f)
                self.agronomic_guidance = km_data.get("agronomic_guidance", {})

        if os.path.exists(lr_metrics_path):
            with open(lr_metrics_path, "r") as f:
                lr_data = json.load(f)
                self.residual_std = lr_data.get("residual_stats", {}).get("std", 5.13)

    # ──────────────────────────────────────────
    # Styling
    # ──────────────────────────────────────────
    def create_styles(self):
        """Define custom styles for the Dark UI Theme."""
        style = ttk.Style()
        style.theme_use("default")

        style.configure("TFrame", background=BG_MAIN)
        style.configure("Card.TFrame", background=BG_CARD, relief="flat")

        style.configure("TNotebook", background=BG_MAIN, borderwidth=0)
        style.configure("TNotebook.Tab",
                        background=BG_CARD, foreground=TEXT_SILVER,
                        padding=[15, 5], font=("Helvetica", 10, "bold"), borderwidth=0)
        style.map("TNotebook.Tab",
                  background=[("selected", ACCENT_CYAN)],
                  foreground=[("selected", TEXT_DARK)])

        style.configure("TLabel", background=BG_MAIN, foreground=TEXT_WHITE, font=("Helvetica", 10))
        style.configure("Title.TLabel", background=BG_MAIN, foreground=ACCENT_CYAN, font=("Helvetica", 16, "bold"))
        style.configure("Header.TLabel", background=BG_CARD, foreground=TEXT_WHITE, font=("Helvetica", 12, "bold"))
        style.configure("ResultTitle.TLabel", background=BG_CARD, foreground=ACCENT_PURPLE, font=("Helvetica", 10, "bold"))
        style.configure("ResultValue.TLabel", background=BG_CARD, foreground=TEXT_WHITE, font=("Helvetica", 14, "bold"))

        style.configure("TEntry", fieldbackground=BG_MAIN, foreground=TEXT_WHITE, insertcolor=TEXT_WHITE, borderwidth=1)

        style.configure("TButton", background=ACCENT_CYAN, foreground=TEXT_DARK,
                        font=("Helvetica", 10, "bold"), padding=[10, 5], borderwidth=0)
        style.map("TButton",
                  background=[("active", ACCENT_PURPLE)],
                  foreground=[("active", TEXT_WHITE)])

        style.configure("Secondary.TButton", background=BG_CARD, foreground=TEXT_SILVER,
                        font=("Helvetica", 9), padding=[8, 4], borderwidth=0)
        style.map("Secondary.TButton",
                  background=[("active", ACCENT_CYAN)],
                  foreground=[("active", TEXT_DARK)])

    # ──────────────────────────────────────────
    # UI Construction
    # ──────────────────────────────────────────
    def build_ui(self):
        """Construct the dashboard grids and panels."""
        self.columnconfigure(0, weight=4)
        self.columnconfigure(1, weight=5)
        self.rowconfigure(0, weight=0)
        self.rowconfigure(1, weight=1)
        self.rowconfigure(2, weight=1)

        # ── HEADER BAR ──
        header_frame = ttk.Frame(self, padding=10)
        header_frame.grid(row=0, column=0, columnspan=2, sticky="ew")

        title_lbl = ttk.Label(header_frame, text="SMART AGRICULTURE DECISION SUPPORT SYSTEM (DSS)", style="Title.TLabel")
        title_lbl.pack(side="left")

        status_text = "Models Loaded" if self.models_loaded else "Model Error"
        status_color = ACCENT_GREEN if self.models_loaded else ACCENT_ORANGE
        status_lbl = ttk.Label(header_frame, text=status_text,
                               foreground=status_color, font=("Helvetica", 10, "bold"))
        status_lbl.pack(side="right")

        # ── LEFT PANEL: Parameter Inputs ──
        input_card = ttk.Frame(self, style="Card.TFrame", padding=15)
        input_card.grid(row=1, column=0, sticky="nsew", padx=10, pady=10)
        input_card.columnconfigure(0, weight=1)
        input_card.columnconfigure(1, weight=2)

        input_header = ttk.Label(input_card, text="Environmental & Soil Parameters", style="Header.TLabel")
        input_header.grid(row=0, column=0, columnspan=2, sticky="w", pady=(0, 15))

        self.input_vars = {}
        features_info = [
            ("N", "Nitrogen (kg/ha)", "90", "0 to 140"),
            ("P", "Phosphorus (kg/ha)", "42", "5 to 145"),
            ("K", "Potassium (kg/ha)", "43", "5 to 205"),
            ("ph", "Soil pH", "6.5", "3.5 to 9.9"),
            ("temperature", "Temperature (°C)", "20.8", "10 to 45"),
            ("humidity", "Relative Humidity (%)", "82.0", "15 to 100"),
            ("rainfall", "Rainfall (mm)", "202.9", "20 to 300")
        ]

        row_idx = 1
        for key, name, default, limit in features_info:
            lbl = ttk.Label(input_card, text=name, background=BG_CARD, font=("Helvetica", 10, "bold"))
            lbl.grid(row=row_idx, column=0, sticky="w", pady=6)

            var = tk.StringVar(value=default)
            self.input_vars[key] = var

            entry = ttk.Entry(input_card, textvariable=var, font=("Helvetica", 10))
            entry.grid(row=row_idx, column=1, sticky="ew", pady=6, padx=(10, 0))

            bound_lbl = ttk.Label(input_card, text=f"Range: {limit}", background=BG_CARD,
                                  foreground=TEXT_SILVER, font=("Helvetica", 8))
            bound_lbl.grid(row=row_idx + 1, column=1, sticky="w", padx=(10, 0), pady=(0, 5))

            row_idx += 2

        # Control Buttons
        btn_frame = ttk.Frame(input_card, style="Card.TFrame")
        btn_frame.grid(row=row_idx, column=0, columnspan=2, pady=15, sticky="ew")
        btn_frame.columnconfigure(0, weight=1)
        btn_frame.columnconfigure(1, weight=1)

        load_btn = ttk.Button(btn_frame, text="Load Rice Preset", command=self.load_preset, style="Secondary.TButton")
        load_btn.grid(row=0, column=0, padx=(0, 5), sticky="ew")

        run_btn = ttk.Button(btn_frame, text="Analyze & Predict", command=self.run_predictions)
        run_btn.grid(row=0, column=1, padx=(5, 0), sticky="ew")

        # ── RIGHT PANEL: Integrated Results ──
        output_card = ttk.Frame(self, style="Card.TFrame", padding=15)
        output_card.grid(row=1, column=1, sticky="nsew", padx=10, pady=10)

        output_header = ttk.Label(output_card, text="Agronomic Analysis & Recommendations", style="Header.TLabel")
        output_header.pack(anchor="w", pady=(0, 15))

        # Crop recommendation card
        crop_frame = ttk.Frame(output_card, style="Card.TFrame", borderwidth=1, relief="solid")
        crop_frame.pack(fill="x", pady=5)
        ttk.Label(crop_frame, text="RECOMMENDED CROP TYPE", style="ResultTitle.TLabel").pack(anchor="w", padx=10, pady=(5, 0))
        self.crop_res_val = ttk.Label(crop_frame, text="Waiting for analysis...",
                                       style="ResultValue.TLabel", foreground=ACCENT_CYAN)
        self.crop_res_val.pack(anchor="w", padx=10, pady=(0, 10))

        # Soil cluster card
        soil_frame = ttk.Frame(output_card, style="Card.TFrame", borderwidth=1, relief="solid")
        soil_frame.pack(fill="x", pady=5)
        ttk.Label(soil_frame, text="ASSIGNED SOIL PROFILE CLUSTER", style="ResultTitle.TLabel").pack(anchor="w", padx=10, pady=(5, 0))
        self.soil_res_val = ttk.Label(soil_frame, text="Waiting for analysis...",
                                       style="ResultValue.TLabel", foreground=ACCENT_PURPLE)
        self.soil_res_val.pack(anchor="w", padx=10, pady=(0, 5))

        self.soil_guidance_text = tk.Text(
            soil_frame, height=5, bg=BG_CARD, fg=TEXT_SILVER,
            font=("Helvetica", 9), wrap="word", bd=0, highlightthickness=0
        )
        self.soil_guidance_text.pack(fill="x", padx=15, pady=(0, 10))
        self.soil_guidance_text.insert("1.0", "Agronomic instructions will be generated after prediction...")
        self.soil_guidance_text.config(state="disabled")

        # Yield forecast card
        yield_frame = ttk.Frame(output_card, style="Card.TFrame", borderwidth=1, relief="solid")
        yield_frame.pack(fill="x", pady=5)
        ttk.Label(yield_frame, text="FORECASTED CROP YIELD", style="ResultTitle.TLabel").pack(anchor="w", padx=10, pady=(5, 0))
        self.yield_res_val = ttk.Label(yield_frame, text="Waiting for analysis...",
                                        style="ResultValue.TLabel", foreground=ACCENT_GREEN)
        self.yield_res_val.pack(anchor="w", padx=10, pady=(0, 2))

        self.yield_bounds_val = ttk.Label(yield_frame, text="", background=BG_CARD,
                                           foreground=TEXT_SILVER, font=("Helvetica", 9, "italic"))
        self.yield_bounds_val.pack(anchor="w", padx=10, pady=(0, 10))

        # ── BOTTOM PANEL: Visualizations Dashboard ──
        viz_panel = ttk.Frame(self)
        viz_panel.grid(row=2, column=0, columnspan=2, sticky="nsew", padx=10, pady=(0, 10))

        self.notebook = ttk.Notebook(viz_panel)
        self.notebook.pack(fill="both", expand=True)

        self.tab1 = ttk.Frame(self.notebook)
        self.tab2 = ttk.Frame(self.notebook)
        self.tab3 = ttk.Frame(self.notebook)

        self.notebook.add(self.tab1, text="Feature Importance")
        self.notebook.add(self.tab2, text="Soil Cluster PCA")
        self.notebook.add(self.tab3, text="Residual Analysis")

        # Load pre-rendered PNG plots into tabs
        self._photo_refs = []  # prevent garbage collection
        self._load_plot_tab(self.tab1, PLOT_FEATURE_IMPORTANCE, "Feature Importance Plot")
        self._load_plot_tab(self.tab2, PLOT_CLUSTER_SCATTER, "Soil Cluster PCA Plot")
        self._load_plot_tab(self.tab3, PLOT_RESIDUAL, "Residual Analysis Plot")

    def _load_plot_tab(self, tab: ttk.Frame, image_path: str, fallback_text: str):
        """Load a pre-rendered PNG image into a notebook tab using native tk.PhotoImage."""
        if os.path.exists(image_path):
            try:
                photo = tk.PhotoImage(file=image_path)
                # Subsample to fit within the tab (PNG may be very large at 150 DPI)
                # Original images are ~1500px wide at 150 DPI; scale to ~750px
                photo = photo.subsample(2, 2)
                self._photo_refs.append(photo)

                canvas = tk.Canvas(tab, bg=BG_CARD, highlightthickness=0)
                canvas.pack(fill="both", expand=True)

                # Center the image
                canvas.create_image(0, 0, anchor="nw", image=photo)
                canvas.config(scrollregion=canvas.bbox("all"))

                # Add scrollbars for large images
                h_scroll = ttk.Scrollbar(tab, orient="horizontal", command=canvas.xview)
                v_scroll = ttk.Scrollbar(tab, orient="vertical", command=canvas.yview)
                canvas.configure(xscrollcommand=h_scroll.set, yscrollcommand=v_scroll.set)
                h_scroll.pack(side="bottom", fill="x")
                v_scroll.pack(side="right", fill="y")

            except Exception as e:
                logger.error(f"Failed to load plot {image_path}: {e}")
                lbl = tk.Label(tab, text=f"Could not load: {e}", bg=BG_CARD, fg=TEXT_SILVER,
                               font=("Helvetica", 11))
                lbl.pack(expand=True)
        else:
            lbl = tk.Label(tab, text=f"{fallback_text}\n(Run models.py first to generate plots)",
                           bg=BG_CARD, fg=TEXT_SILVER, font=("Helvetica", 11), justify="center")
            lbl.pack(expand=True)

    # ──────────────────────────────────────────
    # Preset & Prediction Logic
    # ──────────────────────────────────────────
    def load_preset(self):
        """Load a valid preset for immediate testing (Rice crop parameters)."""
        presets = {
            "N": "90", "P": "42", "K": "43", "ph": "6.5",
            "temperature": "20.8", "humidity": "82.0", "rainfall": "202.9"
        }
        for key, val in presets.items():
            self.input_vars[key].set(val)

    def run_predictions(self):
        """Sequential inference pipeline triggered by user submission."""
        if not self.models_loaded:
            messagebox.showerror("Error", "ML Models are not loaded. Cannot run inference.")
            return

        # Parse & validate inputs
        inputs = []
        raw_vals = {}
        for key in ALL_FEATURES:
            try:
                val = float(self.input_vars[key].get().strip())
                inputs.append(val)
                raw_vals[key] = val
            except ValueError:
                messagebox.showerror("Input Validation Error",
                                     f"Please enter a valid numeric value for '{key}'.")
                return

        if not (0 <= raw_vals["ph"] <= 14):
            messagebox.showerror("Validation Error", "Soil pH must be between 0 and 14.")
            return

        feature_vector = np.array(inputs).reshape(1, -1)

        try:
            # 1. Decision Tree — Crop Recommendation
            recommended_crop = self.dt_clf.predict(feature_vector)[0]
            self.crop_res_val.config(text=str(recommended_crop).upper())

            # 2. K-Means — Soil Cluster Assignment
            soil_vector = np.array([raw_vals["N"], raw_vals["P"], raw_vals["K"], raw_vals["ph"]]).reshape(1, -1)
            soil_scaled = self.soil_scaler.transform(soil_vector)
            assigned_cluster = int(self.kmeans.predict(soil_scaled)[0])
            self.soil_res_val.config(text=f"CLUSTER ID: {assigned_cluster}")

            # Agronomic guidance
            guidance_list = self.agronomic_guidance.get(str(assigned_cluster), [
                "Ensure standard macro-nutrient levels.",
                "Conduct regular soil quality assays."
            ])
            formatted_guidance = "\n".join([f"• {g}" for g in guidance_list])

            self.soil_guidance_text.config(state="normal")
            self.soil_guidance_text.delete("1.0", tk.END)
            self.soil_guidance_text.insert("1.0", formatted_guidance)
            self.soil_guidance_text.config(state="disabled")

            # 3. Linear Regression — Yield Forecast
            predicted_yield = self.lr_model.predict(feature_vector)[0]
            predicted_yield = max(0.1, predicted_yield)

            lower_bound = max(0.0, predicted_yield - 1.96 * self.residual_std)
            upper_bound = predicted_yield + 1.96 * self.residual_std

            self.yield_res_val.config(text=f"{predicted_yield:.2f} metric tons per hectare")
            self.yield_bounds_val.config(
                text=f"95% Confidence Range: [{lower_bound:.2f} — {upper_bound:.2f}] tons/ha"
            )

            logger.info(f"Inference complete: crop={recommended_crop}, "
                        f"cluster={assigned_cluster}, yield={predicted_yield:.2f}")

        except Exception as e:
            logger.error(f"Inference pipeline error: {e}")
            messagebox.showerror("Pipeline Failure", f"An error occurred during prediction:\n{e}")


if __name__ == "__main__":
    app = SmartAgriGUI()
    app.mainloop()
